services:
  - type: web
    name: apk-safety-analyzer
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 4
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
